[package]
name = "vanity"
version = "0.3.4"
authors = ["Boban Acimovic <boban.acimovic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.42"
confy = { version = "0.4.0", default-features = false, features = ["yaml_conf"] }
json_env_logger = { version = "0.1.1", features = ["iso-timestamps"] }
log = ">=0.4.13, <0.4.14" # restricted because json_env_logger compile failes with newer versions
serde = "1.0.126"
serde_derive = "1.0.126"
tokio = { version = "1.9.0", features = ["full"] }
warp = "0.3.1"

[patch.crates-io]
confy = { git = 'https://github.com/rust-cli/confy' }
