apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vanity.fullname" . }}
  labels: {{- include "vanity.labels" . | nindent 4 }}
data:
  config: |
    {{- toYaml .Values.config | nindent 4 }}
