name: chart

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/charts/vanity/**'
  pull_request:
    paths:
      - 'deploy/charts/vanity/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Set up cache
        uses: actions/cache@v2.1.4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up linters
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          GO111MODULE=on go get golang.stackrox.io/kube-linter/cmd/kube-linter

      - name: Check out
        uses: actions/checkout@v2

      - name: Lint
        run: |
          helm lint deploy/charts/vanity
          # TODO: fix linting problems and set linter to fail
          kube-linter lint deploy/charts/vanity || true
