name: pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    uses: ectobit/reusable-workflows/.github/workflows/rust-check.yaml@main
  build:
    uses: ectobit/reusable-workflows/.github/workflows/buildx.yaml@main
    needs: check
    with:
      image: ectobit/vanity
      hadolint-ignore: DL3006
      platforms: linux/amd64
    secrets:
      container-registry-username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      container-registry-password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
